const assert = require('node:assert/strict');
const fs = require('node:fs');
const ui = require('./delivery-ui.js');
const fixture = JSON.parse(fs.readFileSync('frontend/tests/fixtures/delivery-reliance.json','utf8'));
const html=ui.render(fixture);
assert(html.includes(fixture.summary.latest.toFixed(2)+'%'));
assert(html.includes(fixture.summary.avg_20.toFixed(2)+'%'));
assert(html.includes(fixture.summary.year_sessions+' sessions held'));
assert.match(html,/13\.20 L/);
assert.match(html,/13,20,000 shares, derived/);
assert.match(html,/delivered quantity|Delivered quantity/);
assert.match(html,/stroke-dasharray="66 100"/);
assert.match(html,/0–100% scale/);
assert.match(html,/<details class="dv-data">/);
assert(!html.includes('NaN'));
for(const x of [null,undefined,'',NaN,Infinity,-1,101]) assert.equal(ui.percent(x),null);
assert.equal(ui.percent(0),0);
assert.equal(ui.percent(100),100);
const missing=ui.render({available:true,summary:{latest:null},rows:[{date:'2026-09-01',deliv_pct:null,delivered_qty:null,traded_qty:null,close:null}]});
assert.doesNotMatch(missing,/dv-ring-fill|0\.00%|NaN|undefined|0 shares/);
assert.match(missing,/<dd>—<\/dd>/);
const gapped=ui.chart([{date:'2026-09-01',deliv_pct:20},{date:'2026-09-02',deliv_pct:null},{date:'2026-09-03',deliv_pct:40}],30);
const path=gapped.match(/class="dv-trend-line"[^>]*d="([^"]*)"/)[1];
assert.equal((path.match(/ M/g)||[]).length,2,'missing readings break the line');
assert(!path.includes(' L'));
assert.match(ui.render({summary:{},rows:[]}),/No session history/);
assert.match(ui.render({symbol:'<img src=x>',summary:{},rows:[]}),/&lt;img src=x&gt;/);
assert.doesNotMatch(ui.render({symbol:'<img src=x>',summary:{},rows:[]}),/<img/);
let input;
const slider={value:'0',addEventListener:(kind,fn)=>{input=fn;},setAttribute:(key,value)=>{slider[key]=value;}};
const selected={innerHTML:''};
const host={innerHTML:'',querySelector:sel=>sel==='#dv-session-slider'?slider:selected};
ui.mount(host,fixture);input();
const oldest=fixture.rows.slice().sort((a,b)=>a.date.localeCompare(b.date))[0];
assert.match(selected.innerHTML,new RegExp(oldest.deliv_pct.toFixed(2)+'%'));
assert(slider['aria-valuetext'].includes(oldest.date));
assert.deepEqual(fixture,JSON.parse(fs.readFileSync('frontend/tests/fixtures/delivery-reliance.json','utf8')),'input is not mutated');
console.log('Delivery UI: exact data, missing values, chart gaps, disclosure, escaping and session selection passed');
