'use strict';
const assert = require('node:assert/strict');
const {compare,snapshot,build,safeURL}=require('./portfolio-intelligence.js');
function snap(overrides={}){return {at:'2026-09-10T10:00:00Z',basis:{version:1,benchmark:'March 2026'},score:70,coverage:100,holdings:[{symbol:'A',score:70,qty:1}],sectors:[{sector:'Energy',weight:100}],events:[],...overrides};}
assert.deepEqual(compare(null,snap()),[]);
assert.deepEqual(compare(snap(),snap()),[]);
assert.deepEqual(compare(snap(),snap({at:'2026-09-11',basis:{version:2}})),[]);
assert.deepEqual(compare(snap(),snap({at:'2026-09-11',coverage:50,score:80})),[]);
assert.ok(compare(snap(),snap({at:'2026-09-11',score:80}))[0].includes('70.0 → 80.0'));
assert.ok(compare(snap(),snap({at:'2026-09-11',holdings:[{symbol:'B',score:70}],sectors:[{sector:'Technology',weight:100}]})).some(x=>x.includes('Energy exposure 100.0% → 0.0%')));
assert.equal(safeURL('javascript:alert(1)'),null);
assert.equal(safeURL('https://nseindia.com/a.pdf'),'https://nseindia.com/a.pdf');
const html=build({holdings:[],failed:[{symbol:'<script>alert(1)</script>',error:'Unavailable'}],data_quality:{},risk:{},history:{},sectors:[],sector_comparison:[]});
assert.ok(html.includes('&lt;script&gt;'));
assert.ok(!html.includes('<script>alert'));
assert.ok(html.includes('Partial valuation'));
assert.ok(html.includes('No positive market values available'));
assert.ok(!html.includes('NaN'));
assert.ok(!html.includes('What Changed Recently'));
console.log('Portfolio Intelligence: 14 frontend assertions passed');
const sample={holdings:[{symbol:'LARGE',weight_pct:60,pnl:-500,value:6000},{symbol:'SMALL',weight_pct:40,pnl:100,value:4000}],total_value:10000,sectors:[{sector:'Energy',weight_pct:100}],data_quality:{valuation_complete:true,cost_value_pct:100,scored_value_pct:100},policy:{max_stock_pct:20,max_sector_pct:40}};
const simple=build(sample);
assert.ok(simple.includes('pi-mode-simple'));
assert.ok(simple.includes('About ₹60 of every ₹100'));
assert.ok(simple.includes('Loss ₹500'));
assert.ok(simple.includes('Gain ₹100'));
assert.ok(simple.includes('above your 20.0% stock limit'));
assert.ok(simple.includes('above your 40.0% sector limit'));
assert.ok(build({...sample,data_quality:{}}).includes('not your complete portfolio return'));
assert.ok(build({...sample,holdings:[]}).includes('Add purchase prices'));
assert.ok(build(sample,true).includes('pi-mode-advanced'));
assert.ok(!build(sample,true).includes('data-review-mode'));
console.log('Simple portfolio: missing data, priorities, gain/loss and export assertions passed');
